fix/test Record subclassing
Accessing the Record.__dict__ like this would not access the base
classes (as regular attribute access does); causing:

    ======================================================================
    ERROR: Test that Record subclasses work
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File ".../tests/test_visitable.py", line 212, in test_subclassing
        nt = NamedThing(id=123, name="adam")
      File ".../normalize/record/__init__.py", line 24, in __init__
        "unknown property '%s' in %s" % (prop, type(self).__name__)
    Exception: unknown property 'id' in NamedThing

    ----------------------------------------------------------------------